# Generated by `forktex fsd makefile sync`
# Unit: root project
.DEFAULT_GOAL := help
PROJECT_NAME := forktex-core
SUBPACKAGES :=
PUBLISHABLE_PACKAGES := .

help: ## Self-documenting target listing
	@python3 -m forktex.agent.help make --project-dir . || \
		grep -E '^[a-zA-Z_@-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

format: ## Source code conforms to a consistent, auto-enforced style
	poetry run python3 -m ruff format src/ tests/

lint: ## Static analysis catches bugs, anti-patterns, and security issues
	poetry run python3 -m ruff check src/ tests/

typing: ## Static type system verifies interface correctness across the codebase
	@# `poetry run`, not bare `python` — pyright resolves imports from the
	@# interpreter's environment, and `poetry run` is what exports `VIRTUAL_ENV`
	@# for it. Run bare and you get ~210 phantom `reportMissingImports` errors
	@# that look like real type errors. `typecheck` is the same command.
	poetry run python3 -m pyright src/

test: ## Automated tests verify behaviour at the unit and integration level, with a coverage floor
	@# The floor ratchets: it is the measured figure, so coverage cannot silently drop.
	@# Raise it when a pass adds real coverage; never lower it to make a change pass.
	poetry run python3 -m pytest tests/ -q --cov=src/forktex_core --cov-report=term-missing:skip-covered --cov-fail-under=86

security: ## Dependencies and code scanned for known vulnerabilities and security smells
	poetry run python3 -m pip_audit --skip-editable

license: ## Source headers and dependency licenses verified against policy
	poetry run python3 scripts/license_headers.py check

sync: ## Derived artifacts (types, migrations, API stubs, RTK queries, docs) kept in sync with their declarative source of truth
	@echo "$(PROJECT_NAME): sync — no codegen targets declared. Add fsd.atoms.\"sync@<kind>\" overrides in forktex.json (e.g. sync@migration, sync@types, sync@api, sync@docs)."

docs: ## Project documentation exists and is current — architecture diagrams, API reference, runbooks, ADRs
	@echo "$(PROJECT_NAME): docs — declare fsd.atoms.\"docs@<kind>\" overrides (e.g. docs@arch via 'forktex arch c4')."

manual: ## System-wide architecture + context manual generated from the project graph (humans + agents). Renders C4 + filesystem inspector + dependency map for humans, plus an AI-consumable bundle of rules / concepts / few-shots for downstream agentic workflows.
	@echo "$(PROJECT_NAME): manual — declare fsd.atoms.\"manual\" or use 'forktex arch build' (graph diagrams + grounding bundle)."

install: ## Project bootstraps to a runnable state on a fresh machine — auto-detects the OS, missing tools (poetry/uv/.venv/node_modules/pyright), and resolves them
	@if command -v poetry >/dev/null 2>&1; then \
		echo "  install: poetry detected → poetry install --with dev"; \
		poetry install --with dev; \
	elif [ -d .venv ]; then \
		echo "  install: .venv detected → pip install -e ."; \
		.venv/bin/pip install -e .; \
	elif command -v pip >/dev/null 2>&1; then \
		echo "  install: pip --user fallback → pip install --user -e ."; \
		pip install --user -e . 2>/dev/null || pip install --break-system-packages -e .; \
	else \
		echo "  install: no python toolchain found. Install Python ≥ 3.14 first."; \
		exit 1; \
	fi
	@echo ""
	@echo "$(PROJECT_NAME) installed."

build: ## Build sdist + wheel into dist/ and verify metadata with twine check
	rm -rf dist/
	poetry run python3 -m build
	poetry run python3 -m twine check dist/*

publish: ## Upload dist/ to production PyPI (irreversible per-version)
	poetry run python3 -m twine upload dist/*

clean: ## Build artifacts and caches removable from project tree
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name .pytest_cache -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name .ruff_cache -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name .mypy_cache -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name dist -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name build -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null; true
	find . -type d -name htmlcov -exec rm -rf {} + 2>/dev/null; true
	find . -type f -name .coverage -delete 2>/dev/null; true

apply: ## Drive a runtime to its declared state — local process, local compose, or env-orchestrated deploy. Idempotent.
	@$(MAKE) install
	@echo ""
	@echo "$(PROJECT_NAME) runtime ready."
	@echo "  Run: forktex --version"
	@echo "  Run: make test"
	@echo ""

destroy: ## Remove a runtime entirely — terminate processes, tear down env infrastructure
	@echo "$(PROJECT_NAME) has no managed long-running runtime locally."
	@echo "  For env teardown declare fsd.atoms.\"destroy@<env>\" in forktex.json."

monitor: ## Inspect current runtime state — health, metrics, replica status, and live event/log streams
	@echo "$(PROJECT_NAME): monitor — declare fsd.atoms.\"monitor@<env>\" (health, metrics, logs) or use 'forktex cloud' (deploy & observe)."

acceptance: ## End-to-end verification that a deployed runtime works against real infrastructure (battle, e2e, load, chaos, pen)
	@echo "$(PROJECT_NAME): acceptance — declare fsd.atoms.\"acceptance@<scope>\" (e.g. @battle, @e2e, @load)."

typecheck: ## Static type system verifies interface correctness (pyright; install via dev deps)
	poetry run python3 -m pyright src/

audit: ## Scan the project venv for known CVEs in installed deps. Always uses `poetry run` so pip-audit reads the venv's installed packages, not the system Python (which would surface Ubuntu-shipped jinja2/cloud-init/ansible etc. — irrelevant to this library).
	poetry run python3 -m pip_audit --skip-editable

publish-test: ## Upload dist/ to TestPyPI (https://test.pypi.org) for rehearsal
	poetry run python3 -m twine upload --repository testpypi dist/*

license-check: ## Verify every source file carries the current AGPL-3.0 + Commercial dual-license header (CI gate)
	poetry run python3 scripts/license_headers.py check

license-fix: ## Add or update the dual-license header on every source file (idempotent)
	poetry run python3 scripts/license_headers.py fix

license-strip: ## Remove the dual-license header from every source file (use before license model changes)
	poetry run python3 scripts/license_headers.py strip

codegen: ## Not applicable: forktex-core has no schema-derived artifacts
	@echo 'codegen: not applicable for forktex-core (pure runtime library, no generated code)'

codegen-check: ## Not applicable: forktex-core has no generated artifacts to verify
	@echo 'codegen-check: not applicable for forktex-core'

ci: ## Aggregate quality gate before publish: format-check + lint + license-check + typecheck + audit + test + catalog-check + build + smoke
	@$(MAKE) format-check
	@$(MAKE) lint
	@$(MAKE) license-check
	@$(MAKE) typecheck
	@$(MAKE) audit
	@$(MAKE) test
	@$(MAKE) catalog-check
	@$(MAKE) build
	@$(MAKE) smoke
	@echo ''
	@echo 'CI passed for $(PROJECT_NAME) — safe to: make publish-test  /  make publish'

format-check: ## Check formatting without rewriting files
	poetry run python3 -m ruff format --check src/ tests/

test-perf: ## Run the grid limits/performance suite (opt-in; writes a JSONL artifact under tests/test_grid/test_limits/.runs/). Not gated by `make ci`.
	poetry run python3 -m pytest tests/test_grid/test_limits/ -m perf -q -s

test-perf-headroom: ## Probe the 1M-row tier on operations that survived the main ladder. Slow (minutes); requires FORKTEX_PERF_HEADROOM=1.
	FORKTEX_PERF_HEADROOM=1 poetry run python3 -m pytest tests/test_grid/test_limits/test_headroom.py -m perf -q -s

test-perf-report: ## Render the latest grid perf JSONL artifact as a markdown table (grid_ms / native_ms (Nx)).
	poetry run python3 scripts/grid_perf_report.py

catalog-check: ## README's generated blocks match catalog.json (the machine SSOT)
	poetry run python3 scripts/regenerate_readme.py --check

smoke: ## Install the BUILT wheel into a throwaway venv and import every extra
	@# The gate `make ci` was missing: everything above tests the source tree, so a
	@# packaging fault is invisible to it. `[worker]` shipped documented but
	@# undeclared exactly this way.
	@# Importing the module is NOT sufficient to prove an extra exists — most
	@# modules here import fine without their dependency (it is looked up lazily so
	@# the error can name the extra). pip merely *warns* on an unknown extra and
	@# exits 0, so that warning is what this greps for.
	@set -e; \
	wheel=$$(ls dist/*.whl | head -1); \
	py=$$(poetry run python3 -c 'import sys; print(sys.executable)'); \
	tmp=$$(mktemp -d); \
	trap 'rm -rf $$tmp' EXIT; \
	echo "smoke: base install from $$wheel (interpreter $$py)"; \
	$$py -m venv $$tmp/base >/dev/null; \
	$$tmp/base/bin/pip install -q "$$wheel"; \
	$$tmp/base/bin/python -c "import forktex_core.log, forktex_core.error, forktex_core.types, forktex_core.iso, forktex_core.database, forktex_core.grid, forktex_core.space, forktex_core.flow, forktex_core.graph, forktex_core.catalog; print('  base modules import')"; \
	for x in worker api vault storage queue vector store; do \
	  rm -rf $$tmp/x; $$py -m venv $$tmp/x >/dev/null; \
	  $$tmp/x/bin/pip install "$$wheel[$$x]" >$$tmp/log 2>&1 || { cat $$tmp/log; exit 1; }; \
	  if grep -q "does not provide the extra" $$tmp/log; then \
	    echo "  [$$x] FAIL — pyproject declares no '$$x' extra (pip only warns)"; exit 1; \
	  fi; \
	  $$tmp/x/bin/python -c "import importlib; importlib.import_module('forktex_core.'+'$$x')"; \
	  echo "  [$$x] OK"; \
	done; \
	echo "smoke: every extra resolves and delivers a working module"

test-cov: ## Run the suite with coverage reporting
	poetry run python3 -m pytest tests/ --cov=src --cov-report=term-missing

lint-fix: ## Lint and auto-fix where possible
	poetry run python3 -m ruff check --fix src/ tests/

examples: ## Run every examples/*.py against real testcontainers (Postgres + Redis + MinIO + Qdrant). Opt-in; not gated by `make ci` because it boots four containers.
	poetry run python3 -m scripts.run_examples

deps-lock: ## Lock dependencies
	poetry lock

local: apply

local-down: destroy

local-monitor: monitor

quality: format lint typing ## chord (format + lint + typing)

install-global: ## Install the latest local forktex CLI globally in editable mode
	pip install --break-system-packages -e .

.PHONY: format lint typing test security license sync docs manual install build publish clean apply destroy monitor acceptance typecheck audit publish-test license-check license-fix license-strip codegen codegen-check ci format-check test-perf test-perf-headroom test-perf-report catalog-check smoke test-cov lint-fix examples deps-lock local local-down local-monitor quality install-global
